import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import BottomNavBar from "@/components/BottomNavBar/BottomNavBar";
import { Roboto } from 'next/font/google';

const raleway = Roboto({
  weight: '400', // Usar peso SemiBold
  subsets: ['latin'], // Compatibilidad con caracteres
});

export const metadata: Metadata = {
  title: "Create Next Appx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${raleway.className} antialiased layout-grid`}>
        <Header className="header" />
        <main className="contenido">{children}</main>
        <BottomNavBar className="bottomNavBar" />
      </body>
    </html>
  );
}
